osx_image: xcode8.2
language: objective-c
xcode_project: StackViewController.xcodeproj
xcode_scheme: StackViewControllerTests
xcode_sdk: iphonesimulator9.2
script:
- xcodebuild clean build test -project StackViewController.xcodeproj -scheme StackViewControllerTests
- pod spec lint GZStackViewController.podspec
